#!/bin/bash

echo "🚀 Railway Deployment Helper"
echo "=============================="
echo ""
echo "Option 1: Deploy via Railway CLI"
echo "---------------------------------"
echo "Run these commands:"
echo ""
echo "  cd /home/ubuntu/github_repos/auto_call_system"
echo "  railway login"
echo "  railway init"
echo "  railway up"
echo ""
echo "Option 2: Deploy via GitHub"
echo "----------------------------"
echo "1. Push this code to GitHub"
echo "2. Go to railway.app"
echo "3. Click 'New Project' → 'Deploy from GitHub'"
echo "4. Select your repository"
echo ""
echo "Option 3: Deploy via Railway Web (No CLI)"
echo "------------------------------------------"
echo "1. Create a ZIP of this directory"
echo "2. Go to railway.app/new"
echo "3. Upload the ZIP file"
echo ""
echo "Your code is ready at: /home/ubuntu/github_repos/auto_call_system"
echo ""
